sudo: required
service:
  - docker

before_install:
  - docker build -t kapalal11/react-test -f ./client/Dockerfile.dev ./client/


script:
  - docker run kapalal11/react-test npm test -- --coverage

after_success:
  - docker build -t kapalal11/multi-client  ./client/
  - docker build -t kapalal11/multi-nginx ./nginx
  - docker build -t kapalal11/multi-worker ./worker
  - docker build -t kapalal11/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kapalal11/multi-client
  - docker push kapalal11/multi-nginx
  - docker push kapalal11/multi-worker
  - docker push kapalal11/multi-server 

deploy:
 provider: elasticbeanstalk
 region: eu-west-3
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-eu-west-3-624758150896
 bucket_path: multi-docker
 on:
    branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
   secure: $AWS_SECRET_KEY
